// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/ivan/PES/PES_HappyLungs/src/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/ivan/PES/PES_HappyLungs/src/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('happyLungs', appParameters);
});
require('/home/ivan/PES/PES_HappyLungs/src/index.js');