const ca = {
	welcome: "Benvingut de nou!",
	filter: "Filtrar",
	typeOfContamination: "Tipus de contaminació",
	typeOfContamination1: "Tràfic",
	typeOfContamination2: "Indústria",
	typeOfContamination3: "Urbà",
	showPins: "Mostrar pins",
	filterByCertificate: "Filtrar edificis per certificat energètic",
	selectedLocation: "Ubicació seleccionada",
	createPin: "Crear Pin",
	seeStatistics: "Veure Estatístiques",
	seeOnMap: "Veure en el mapa",
	share: "Compartir",
	recommended1: "Recomanat",
	recommended2: "No recomanat",
	createdPins: "Pins creats",
	sharedPins: "Pins compartits",
	points: "punts",
	healthState: "Estat de Salut",
	healthState1: "Problemes respiratoris",
	healthState2: "Embaraç",
	healthState3: "Edat avançada",
	settings: "Configuració",
	calendar: "Calendari",
	ranking: "Rànquing",
	shareOption: "Avisa als teus amics",
	logOut: "Tancar sessió",
	editingProfile: "Editar perfil",
	username: "Nom d'usuari",
	email: "Correu electrònic",
	password: "Contrasenya",
	actualPassword: "Contrasenya actual",
	newPassword: "Nova contrasenya",
	confirmNewPassword: "Confirmar nova contrasenya",
	upload: "Penjar",
	cancel: "Cancel·lar",
	accept: "Acceptar",
	update: "Actualitzar",
	myPins: "Els meus Pins",
	search: "Buscar",
	mostRecent: "Més recent",
	bestRated: "Millor valorat",
	created: "Creat",
	saved: "Guardat",
	edit: "Editar",
	delete: "Eliminar",
	public: "Public",
	private: "Privat",
	editingPin: "Editar pin",
	location: "Ubicació",
	title: "Títol",
	description: "Descripció",
	date: "Data",
	pictures: "Imatges",
	rate: "Valoració",
	allowOption: "Permetre a altres usuaris veure aquest pin?",
	allowOption1: "Aquest pin serà visible a la resta d'usuaris.",
	allowOption2: "Aquest pin només el podràs consultar tú.",
	saveChanges: "Guardar canvis",
	confirmationTitle: "Estàs segur?",
	confirmationText:
		"De veritat vols eliminar aquest pin? Aquesta acció és irreversible",
	chat: "Xats",
	newChat: "Nou xat",
};

const en = {
	welcome: "Welcome back!",
	filter: "Filter",
	typeOfContamination: "Type of contamination",
	typeOfContamination1: "Traffic",
	typeOfContamination2: "Industry",
	typeOfContamination3: "Urban",
	showPins: "Show pins",
	filterByCertificate: "Filter buildings by energy certificate",
	selectedLocation: "Selected location",
	createPin: "Create Pin",
	seeStatistics: "See Statistics",
	seeOnMap: "See on Map",
	share: "Share",
	recommended1: "Recommended",
	recommended2: "Not recommended",
	createdPins: "Created pins",
	sharedPins: "Shared pins",
	points: "points",
	healthState: "Health State",
	healthState1: "Cardiorespiratory problems",
	healthState2: "Pregnancy",
	healthState3: "Elderly",
	settings: "Settings",
	calendar: "Calendario",
	ranking: "Ranking",
	shareOption: "Tell your friends",
	logOut: "Logout",
	editingProfile: "Edit profile",
	username: "Username",
	email: "Email",
	password: "Password",
	actualPassword: "Actual password",
	newPassword: "New password",
	confirmNewPassword: "Confirm new password",
	upload: "Upload",
	cancel: "Cancel",
	accept: "Accept",
	update: "Update",
	myPins: "My Pins",
	search: "Search",
	mostRecent: "Most recent",
	bestRated: "Best rated",
	created: "Created",
	saved: "Saved",
	edit: "Edit",
	delete: "Delete",
	public: "Public",
	private: "Private",
	editingPin: "Edit pin",
	location: "Location",
	title: "Title",
	description: "Description",
	date: "Date",
	pictures: "Pictures",
	rate: "Rating",
	allowOption: "Allow others to view this pin?",
	allowOption1: "This pin will be visible to other people.",
	allowOption2: "This ìn will only be visible to you.",
	saveChanges: "Save changes",
	confirmationTitle: "Are you sure?",
	confirmationText:
		"Do you really want to delete this pin? This cannot be undone.",
	chat: "Chats",
	newChat: "New chat",
};

const es = {
	welcome: "Bienvenido de nuevo!",
	filter: "Filtrar",
	typeOfContamination: "Tipo de contaminación",
	typeOfContamination1: "Tráfico",
	typeOfContamination2: "Industria",
	typeOfContamination3: "Urbano",
	showPins: "Mostrar pins",
	filterByCertificate: "Filtrar edificios según certificado energético",
	selectedLocation: "Ubicación selecionada",
	createPin: "Crear Pin",
	seeStatistics: "Ver Estadísticas",
	seeOnMap: "Ver en el mapa",
	share: "Compartir",
	recommended1: "Recomendado",
	recommended2: "No recomendado",
	createdPins: "Pins creados",
	sharedPins: "Pins compartidos",
	points: "puntos",
	healthState: "Estado de Salud",
	healthState1: "Problemas respiratorios",
	healthState2: "Embarazo",
	healthState3: "Edad avanzada",
	settings: "Configuración",
	calendar: "Calendar",
	ranking: "Ranking",
	shareOption: "Avisa a tus amigos",
	logOut: "Cerrar sesión",
	editingProfile: "Editar perfil",
	username: "Nombre de usuario",
	email: "Correo electrónico",
	password: "Contraseña",
	actualPassword: "Contraseña actual",
	newPassword: "Nueva contraseña",
	confirmNewPassword: "Confirmar nueva contraseña",
	upload: "Subir",
	cancel: "Cancelar",
	accept: "Aceptar",
	update: "Actualizar",
	myPins: "Mis Pins",
	search: "Buscar",
	mostRecent: "Más reciente",
	bestRated: "Mejor valorado",
	created: "Creado",
	saved: "Guardado",
	edit: "Editar",
	delete: "Eliminar",
	public: "Público",
	private: "Privado",
	editingPin: "Editar pin",
	location: "Ubicación",
	title: "Título",
	description: "Descripción",
	date: "Fecha",
	pictures: "Imágenes",
	rate: "Valoración",
	allowOption: "¿Permitir a otros usuarios ver este pin?",
	allowOption1: "Este pin será visible al resto de usuarios.",
	allowOption2: "Este pin solo lo podrás ver tú.",
	saveChanges: "Guardar cambios",
	seeOnMap: "Ver en el mapa",
	confirmationTitle: "¿Estás seguro?",
	confirmationText:
		"¿De verdad quieres eliminar este pin? Esta acción es irreversible.",
	chat: "Chats",
	newChat: "Nuevo chat",
};

export { ca, en, es };
